USE ROLE ACCOUNTADMIN;
-- CREATE DATABASE IF NOT EXISTS THERAREBURGER;
USE DATABASE THERAREBURGER;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE DAILY_SALES (
	BRAND VARCHAR(50),
	REGION VARCHAR(50),
	DATE DATE,
	SALES FLOAT
);
